# Generated by Django 4.2.3 on 2023-07-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('subject', models.CharField(max_length=80)),
                ('messages', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TS', 'Shirts'), ('JR', 'Jersey'), ('CP', 'Cap'), ('HD', 'Hoodie'), ('JS', 'Jogger'), ('JK', 'Jacket')], max_length=2),
        ),
    ]
