# Generated by Django 4.2.3 on 2023-07-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='messages',
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
