# Generated by Django 4.1.4 on 2023-07-13 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
